// Generated by scripts/extract_minimax_h3_runtime_models.py.
// Graph topology is shared with the converter; all Python weight readers are erased.
import Diffusion
import Foundation
import NNC

typealias BlockFloat = BFloat16
typealias VideoFloat = Float16
struct PythonObject {}

enum H3Config {
  static let hiddenSize = 5_376
  static let layers = 50
  static let refinerLayers = 2
  static let heads = 56
  static let headDim = 128
  static let innerAttentionSize = heads * headDim
  static let intermediateSize = 14_336
  static let videoChannels = 24
  static let audioChannels = 32
  static let patch = (t: 1, h: 2, w: 2)
  static let videoPatchSize = videoChannels * patch.t * patch.h * patch.w
  static let textSize = 5_120
  static let timestepFrequencySize = 256
  static let timestepHiddenSize = 5_376
  static let timestepSize = 2_688
  static let ropeFrequencySize = 16
  static let rotarySize = 2 * 3 * ropeFrequencySize
  static let ropeTheta: Double = 10_000
  static let normEpsilon: Float = 1e-5
  static let modalityCount = 3

  static let fps = 24
  static let audioLatentsPerSecond = 40
  static let audioOutputRate = 32_000
  static let videoSpatialCompression = 16
  static let framesPerChunk = 17
  static let latentsPerChunk = 5
  static let videoTokenDrop = 3
  static let defaultFrames = 124
  static let defaultHeight = 768
  static let defaultWidth = 1_344
  static let videoFlowShift: Float = 12
  static let audioFlowShift: Float = 3
}

enum H3QwenConfig {
  static let hiddenSize = 5_120
  static let layers = 64
  static let featureLayer = 50
  static let heads = 64
  static let keyValueHeads = 8
  static let headDim = 128
  static let intermediateSize = 25_600
  static let vocabularySize = 151_936
  static let normEpsilon: Float = 1e-6
  static let ropeTheta: Double = 5_000_000
}

enum H3VideoDecoderConfig {
  static let width = 2_048
  static let layers = 36
  static let heads = 32
  static let headDim = 64
  static let intermediateSize = 8_192
  static let rotarySize = 48
  static let registerTokens = 4
  static let spatialPatch = 16
  static let temporalPatch = 4
  static let normEpsilon: Float = 1e-5
}

enum H3ConditioningVideoEncoderConfig {
  static let channels = [128, 256, 256, 512, 512, 1_024]
  static let spatialStrides = [2, 2, 2, 2, 1, 1]
  static let temporalStrides = [1, 2, 2, 1, 1, 1]
  static let blocksPerLevel = 2
  static let latentChannels = 24
  static let normEpsilon: Float = 1e-6
}

enum H3Tag: Int32 {
  case video = 0
  case text = 1
  case audio = 2
}

struct H3PackedLayout {
  let sequenceLength: Int
  let textRange: Range<Int>
  let audioRange: Range<Int>
  let videoRange: Range<Int>
  let positionIDs: Tensor<Float>
  let tokenTags: [Int32]
}

func alignFrameCount(_ requested: Int) -> Int {
  precondition(requested > 0)
  // A single image is encoded / decoded directly by the official VAE rather than going
  // through its 17-frame temporal chunking path.
  if requested == 1 { return 1 }
  var count = requested
  while count % H3Config.framesPerChunk != H3Config.latentsPerChunk {
    count += 1
  }
  return count
}

func videoLatentFrameCount(_ frames: Int) -> Int {
  if frames == 1 { return 1 }
  precondition(frames % H3Config.framesPerChunk == H3Config.latentsPerChunk)
  return (frames - H3Config.latentsPerChunk) / H3Config.framesPerChunk
    * H3Config.latentsPerChunk + 2
}

func audioLatentFrameCount(_ frames: Int) -> Int {
  Int((Double(frames) / Double(H3Config.fps) * Double(H3Config.audioLatentsPerSecond)).rounded())
}

struct H3VideoTilePlan {
  let starts: [Int]
  let lengths: [Int]
  let overlaps: [Int]
}

func splitVideoTiles(length: Int, tileSize: Int = 256, minimumOverlap: Int = 64)
  -> H3VideoTilePlan
{
  precondition(length > 0 && tileSize > 0 && minimumOverlap >= 0)
  if tileSize >= length {
    return H3VideoTilePlan(starts: [0], lengths: [length], overlaps: [])
  }
  var tileCount = (length + tileSize - 1) / tileSize
  while tileSize * tileCount - minimumOverlap * (tileCount - 1) < length {
    tileCount += 1
  }
  var overlaps = [Int](repeating: minimumOverlap, count: tileCount - 1)
  let remaining = tileSize * tileCount - overlaps.reduce(0, +) - length
  for index in 0..<(remaining / H3Config.videoSpatialCompression) {
    overlaps[index % overlaps.count] += H3Config.videoSpatialCompression
  }
  var starts = [0]
  for index in 0..<(tileCount - 1) {
    starts.append(starts.last! + tileSize - overlaps[index])
  }
  return H3VideoTilePlan(
    starts: starts, lengths: [Int](repeating: tileSize, count: tileCount),
    overlaps: overlaps)
}

struct H3VideoTemporalDecodePlan {
  let framePrePadding: Int
  let tokensPerChunk: Int
  let tokenOverlap: Int
  let frameOverlap: Int
  let paddedTokenCount: Int
  let repeatedTailTokens: Int
  let clipStarts: [Int]
}

func videoTemporalDecodePlan(latentFrames: Int) -> H3VideoTemporalDecodePlan {
  precondition(latentFrames > 0)
  let temporalRatio = H3VideoDecoderConfig.temporalPatch
  let framePrePadding = (temporalRatio - H3Config.framesPerChunk % temporalRatio) % temporalRatio
  let tokensPerChunk =
    (H3Config.framesPerChunk + temporalRatio - 1) / temporalRatio
  let tokenOverlap =
    (tokensPerChunk - H3Config.videoTokenDrop % tokensPerChunk) % tokensPerChunk
  let frameOverlap = max(tokenOverlap * temporalRatio - framePrePadding, 0)
  let tokenCountBeforePadding = latentFrames + H3Config.videoTokenDrop
  let repeatedTailTokens =
    (tokensPerChunk - tokenCountBeforePadding % tokensPerChunk) % tokensPerChunk
  let paddedTokenCount = tokenCountBeforePadding + repeatedTailTokens
  let chunkCount = paddedTokenCount / tokensPerChunk - 1
  return H3VideoTemporalDecodePlan(
    framePrePadding: framePrePadding, tokensPerChunk: tokensPerChunk,
    tokenOverlap: tokenOverlap, frameOverlap: frameOverlap,
    paddedTokenCount: paddedTokenCount, repeatedTailTokens: repeatedTailTokens,
    clipStarts: (0..<chunkCount).map { $0 * tokensPerChunk })
}

func videoDecoderRotary(latentFrames: Int, latentHeight: Int, latentWidth: Int)
  -> Tensor<VideoFloat>
{
  let patchCount = latentFrames * latentHeight * latentWidth
  let suffixCount = H3VideoDecoderConfig.registerTokens + 1
  var rotary = Tensor<VideoFloat>(
    .CPU, .NHWC(1, patchCount + suffixCount, 1, H3VideoDecoderConfig.headDim))
  let frequencyCount = H3VideoDecoderConfig.rotarySize / 6
  let inverseFrequencies = (0..<frequencyCount).map { index in
    pow(100.0, -Double(index) * 6.0 / Double(H3VideoDecoderConfig.rotarySize))
  }
  var row = 0
  for frame in 0..<latentFrames {
    let t = 2 * (Double(frame) + 0.5) / Double(latentFrames) - 1
    for yIndex in 0..<latentHeight {
      let y = 2 * (Double(yIndex) + 0.5) / Double(latentHeight) - 1
      for xIndex in 0..<latentWidth {
        let x = 2 * (Double(xIndex) + 0.5) / Double(latentWidth) - 1
        var angleIndex = 0
        for coordinate in [t, y, x] {
          for inverseFrequency in inverseFrequencies {
            let angle = 2 * Double.pi * coordinate * inverseFrequency
            rotary[0, row, 0, 2 * angleIndex] = VideoFloat(cos(angle))
            rotary[0, row, 0, 2 * angleIndex + 1] = VideoFloat(sin(angle))
            angleIndex += 1
          }
        }
        for index in H3VideoDecoderConfig.rotarySize..<H3VideoDecoderConfig.headDim {
          rotary[0, row, 0, index] = VideoFloat(index % 2 == 0 ? 1 : 0)
        }
        row += 1
      }
    }
  }
  for suffix in 0..<suffixCount {
    for index in 0..<H3VideoDecoderConfig.headDim {
      rotary[0, patchCount + suffix, 0, index] = VideoFloat(index % 2 == 0 ? 1 : 0)
    }
  }
  return rotary
}

func unpatchifyVideoDecoderRows(
  _ rows: Tensor<Float>, latentFrames: Int, latentHeight: Int, latentWidth: Int
) -> Tensor<Float> {
  precondition(rows.shape == [latentFrames * latentHeight * latentWidth, 3 * 4 * 16 * 16])
  let temporalPatch = H3VideoDecoderConfig.temporalPatch
  let spatialPatch = H3VideoDecoderConfig.spatialPatch
  let outputFrames = latentFrames * temporalPatch
  let outputHeight = latentHeight * spatialPatch
  let outputWidth = latentWidth * spatialPatch
  let featureCount = 3 * temporalPatch * spatialPatch * spatialPatch
  var output = Tensor<Float>(
    .CPU, format: .NCHW, shape: [1, 3, outputFrames, outputHeight, outputWidth])
  // The C backend cannot materialize the reference's eight-dimensional tensor view directly.
  // Reorder contiguous CPU storage explicitly; this is also suitable for one decoded spatial tile.
  rows.withUnsafeBytes { sourceBytes in
    output.withUnsafeMutableBytes { outputBytes in
      let source = sourceBytes.baseAddress!.assumingMemoryBound(to: Float.self)
      let destination = outputBytes.baseAddress!.assumingMemoryBound(to: Float.self)
      for frame in 0..<latentFrames {
        for y in 0..<latentHeight {
          for x in 0..<latentWidth {
            let token = (frame * latentHeight + y) * latentWidth + x
            for channel in 0..<3 {
              for patchFrame in 0..<temporalPatch {
                for patchY in 0..<spatialPatch {
                  for patchX in 0..<spatialPatch {
                    let feature =
                      (((channel * temporalPatch + patchFrame) * spatialPatch + patchY)
                        * spatialPatch + patchX)
                    let outputIndex =
                      (((channel * outputFrames + frame * temporalPatch + patchFrame)
                        * outputHeight + y * spatialPatch + patchY) * outputWidth
                        + x * spatialPatch + patchX)
                    destination[outputIndex] = source[token * featureCount + feature]
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  return output
}

private let ropeFrameRescale = 5.0 / 3.0
private let ropeFramesPerLatent = [1.0, 4.0, 4.0, 4.0, 4.0]

func temporalPositionGrid(count: Int, origin: Double) -> [Double] {
  var result = [Double](repeating: 0, count: count)
  var position = origin
  for i in 0..<count {
    result[i] = position
    position += ropeFrameRescale * ropeFramesPerLatent[i % ropeFramesPerLatent.count]
  }
  return result
}

func spatialPositionGrid(dimension: Int, patch: Int, squareRootArea: Double) -> [Double] {
  let count = dimension / patch
  let ratio = Double(dimension) / squareRootArea
  let left = (1 - ratio) / 2
  return (0..<count).map { index in
    // This is numpy.linspace(start, stop, count, endpoint=False), not torch.linspace.
    (left + ratio * Double(index) / Double(count)) * 32
  }
}

func makeT2VALayout(
  textTokenCount: Int, latentFrames: Int, latentHeight: Int, latentWidth: Int,
  audioLatents: Int
) -> H3PackedLayout {
  precondition(latentHeight % H3Config.patch.h == 0)
  precondition(latentWidth % H3Config.patch.w == 0)
  let rowsPerFrame =
    latentHeight / H3Config.patch.h * latentWidth / H3Config.patch.w
  let audioRows = audioLatents * 2
  let videoRows = latentFrames * rowsPerFrame
  let textRange = 0..<textTokenCount
  let audioRange = textRange.upperBound..<(textRange.upperBound + audioRows)
  let videoRange = audioRange.upperBound..<(audioRange.upperBound + videoRows)
  let sequenceLength = videoRange.upperBound

  var positions = Tensor<Float>(.CPU, .WC(sequenceLength, 3))
  for i in textRange {
    positions[i, 0] = Float(i)
    positions[i, 1] = 0
    positions[i, 2] = 0
  }

  let squareRootArea = sqrt(Double(latentHeight * latentWidth))
  let heightGrid = spatialPositionGrid(
    dimension: latentHeight, patch: H3Config.patch.h, squareRootArea: squareRootArea)
  let widthGrid = spatialPositionGrid(
    dimension: latentWidth, patch: H3Config.patch.w, squareRootArea: squareRootArea)
  for channel in 0..<2 {
    for i in 0..<audioLatents {
      let row = audioRange.lowerBound + channel * audioLatents + i
      positions[row, 0] = Float(Double(textTokenCount + i))
      positions[row, 1] = 0
      positions[row, 2] = Float(channel == 0 ? widthGrid.first! : widthGrid.last!)
    }
  }

  let temporalGrid = temporalPositionGrid(count: latentFrames, origin: Double(textTokenCount))
  for frame in 0..<latentFrames {
    for y in 0..<heightGrid.count {
      for x in 0..<widthGrid.count {
        let spatialIndex = y * widthGrid.count + x
        let row = videoRange.lowerBound + frame * rowsPerFrame + spatialIndex
        positions[row, 0] = Float(temporalGrid[frame])
        positions[row, 1] = Float(heightGrid[y])
        positions[row, 2] = Float(widthGrid[x])
      }
    }
  }

  var tags = [Int32](repeating: H3Tag.text.rawValue, count: sequenceLength)
  for i in audioRange { tags[i] = H3Tag.audio.rawValue }
  for i in videoRange { tags[i] = H3Tag.video.rawValue }
  return H3PackedLayout(
    sequenceLength: sequenceLength, textRange: textRange, audioRange: audioRange,
    videoRange: videoRange, positionIDs: positions, tokenTags: tags)
}

func h3RotaryTensor(positionIDs: Tensor<Float>) -> Tensor<BlockFloat> {
  precondition(positionIDs.shape.count == 2 && positionIDs.shape[1] == 3)
  let rows = positionIDs.shape[0]
  var rotary = Tensor<BlockFloat>(.CPU, .NHWC(1, rows, 1, H3Config.headDim))
  for row in 0..<rows {
    for angleIndex in 0..<48 {
      let axis = angleIndex / 16
      let frequencyIndex = angleIndex % 16
      let inverseFrequency = pow(10_000.0, -Double(frequencyIndex) * 2.0 / 32.0)
      let angle = Double(positionIDs[row, axis]) * inverseFrequency
      rotary[0, row, 0, angleIndex * 2] = BlockFloat(cos(angle))
      rotary[0, row, 0, angleIndex * 2 + 1] = BlockFloat(sin(angle))
    }
    for index in 96..<H3Config.headDim {
      rotary[0, row, 0, index] = BlockFloat(index % 2 == 0 ? 1 : 0)
    }
  }
  return rotary
}

func shiftedSigmaGrid(points: Int, shift: Float) -> [Float] {
  precondition(points >= 2 && shift > 0)
  return (0..<points).map { index in
    let base = 1 - Float(index) / Float(points - 1)
    return shift * base / (1 + (shift - 1) * base)
  }
}

func schedulerStep(sample: Float, velocity: Float, timestep: Float, sigma: Float, nextSigma: Float)
  -> Float
{
  let denoised = sample + (1 - timestep) * velocity
  let ratio = nextSigma / sigma
  return ratio * sample + (1 - ratio) * denoised
}

private var h3ActivationDebugCounts = [String: Int]()

func h3DebugActivation(_ input: Model.IO, label: String) -> Model.IO {
  let environment = ProcessInfo.processInfo.environment
  guard environment["H3_DEBUG_ACTIVATIONS"] == "1" else {
    return input
  }
  let blockOutput =
    environment["H3_DEBUG_BLOCK_OUTPUTS"] == "1"
    && label.hasPrefix("transformer_blocks.") && label.hasSuffix(".output")
  let suffixMatch = environment["H3_DEBUG_ACTIVATION_SUFFIX"].map(label.hasSuffix) ?? false
  if let prefix = environment["H3_DEBUG_ACTIVATION_PREFIX"],
    !label.hasPrefix(prefix) && !label.hasPrefix("dit.") && !label.hasPrefix("time_embedder.")
      && !blockOutput && !suffixMatch
  {
    return input
  }
  return input.debug { tensors, _ in
    let call = h3ActivationDebugCounts[label, default: 0]
    h3ActivationDebugCounts[label] = call + 1
    if let requestedCall = environment["H3_DEBUG_ACTIVATION_CALL"].flatMap(Int.init),
      call != requestedCall
    {
      return
    }
    let tensor = Tensor<Float>(from: tensors[0]!).toCPU()
    var maximumMagnitude: Float = 0
    var squaredSum: Double = 0
    var finiteCount = 0
    var nonfiniteCount = 0
    tensor.withUnsafeBytes { bytes in
      let values = bytes.baseAddress!.assumingMemoryBound(to: Float.self)
      let count = bytes.count / MemoryLayout<Float>.stride
      for index in 0..<count {
        let value = values[index]
        if value.isFinite {
          maximumMagnitude = max(maximumMagnitude, abs(value))
          squaredSum += Double(value) * Double(value)
          finiteCount += 1
        } else {
          nonfiniteCount += 1
        }
      }
    }
    let rms = finiteCount > 0 ? sqrt(squaredSum / Double(finiteCount)) : .infinity
    print(
      "H3_ACT label=\(label) call=\(call) max=\(maximumMagnitude) rms=\(rms) "
        + "finite=\(finiteCount) nonfinite=\(nonfiniteCount)")
  }
}

func H3Attention(
  prefix: String, sequenceLength: Int, rotary: Bool, useFloat16: Bool = false, name: String = ""
) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  let rot = rotary ? Input() : nil
  let toQ = Dense(
    count: H3Config.innerAttentionSize, noBias: true,
    flags: useFloat16 ? [.Float16] : [], name: name.isEmpty ? "q" : "\(name)_q")
  let toK = Dense(
    count: H3Config.innerAttentionSize, noBias: true,
    flags: useFloat16 ? [.Float16] : [], name: name.isEmpty ? "k" : "\(name)_k")
  let toV = Dense(
    count: H3Config.innerAttentionSize, noBias: true,
    flags: useFloat16 ? [.Float16] : [], name: name.isEmpty ? "v" : "\(name)_v")
  let normQ = RMSNorm(
    epsilon: H3Config.normEpsilon, axis: [3], name: name.isEmpty ? "norm_q" : "\(name)_norm_q")
  let normK = RMSNorm(
    epsilon: H3Config.normEpsilon, axis: [3], name: name.isEmpty ? "norm_k" : "\(name)_norm_k")
  let projectionInput = useFloat16 ? x.to(.Float16) : x.to(.Float32)
  let qProjected = toQ(projectionInput)
  let kProjected = toK(projectionInput)
  let vProjected = toV(projectionInput)
  let qRaw = (useFloat16 ? qProjected.to(.Float32) : qProjected).reshaped(
    .NHWC(1, sequenceLength, H3Config.heads, H3Config.headDim))
  let kRaw = (useFloat16 ? kProjected.to(.Float32) : kProjected).reshaped(
    .NHWC(1, sequenceLength, H3Config.heads, H3Config.headDim))
  var q = normQ(h3DebugActivation(qRaw, label: "\(prefix).q_raw"))
  var k = normK(h3DebugActivation(kRaw, label: "\(prefix).k_raw"))
  let v = h3DebugActivation(
    vProjected.reshaped(
      .NHWC(1, sequenceLength, H3Config.heads, H3Config.headDim)),
    label: "\(prefix).v")
  if useFloat16 {
    q = q.to(.Float16)
    k = k.to(.Float16)
  }
  if let rot {
    let typedRotary = useFloat16 ? rot.to(.Float16) : rot.to(.Float32)
    q = Functional.cmul(left: q, right: typedRotary)
    k = Functional.cmul(left: k, right: typedRotary)
  }
  let attention = ScaledDotProductAttention(
    scale: 1 / Float(H3Config.headDim).squareRoot(),
    flags: useFloat16 ? [.Float16] : [])
  let attentionOutput: Model.IO
  if useFloat16 {
    attentionOutput = attention(q, k, v).to(.Float32)
  } else {
    // The FP32 control uses BF16 only inside fused attention.
    attentionOutput = attention(q.to(.BFloat16), k.to(.BFloat16), v.to(.BFloat16)).to(.Float32)
  }
  let attended = h3DebugActivation(
    attentionOutput.reshaped([1, sequenceLength, H3Config.innerAttentionSize]),
    label: "\(prefix).attended")
  let out = Dense(
    count: H3Config.hiddenSize, noBias: true,
    flags: useFloat16 ? [.Float16] : [], name: name.isEmpty ? "o" : "\(name)_o")
  let projected = out(useFloat16 ? attended.to(.Float16) : attended)
  let projectedOutput = useFloat16 ? projected.to(.Float32) : projected
  let reader: (PythonObject) -> Void = { _ in }
  if let rot {
    return (
      Model([x, rot], [h3DebugActivation(projectedOutput, label: "\(prefix).out_proj")]),
      reader
    )
  }
  return (
    Model([x], [h3DebugActivation(projectedOutput, label: "\(prefix).out_proj")]), reader
  )
}

func H3SwiGLU(
  prefix: String, scaleFactor: Float? = nil, useFloat16: Bool = false, name: String = ""
) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  let up = Dense(
    count: H3Config.intermediateSize, noBias: true,
    flags: useFloat16 ? [.Float16] : [], name: name.isEmpty ? "up" : "\(name)_up")
  let gate = Dense(
    count: H3Config.intermediateSize, noBias: true,
    flags: useFloat16 ? [.Float16] : [], name: name.isEmpty ? "gate" : "\(name)_gate")
  let down = Dense(
    count: H3Config.hiddenSize, noBias: true,
    flags: useFloat16 ? [.Float16] : [], name: name.isEmpty ? "down" : "\(name)_down")
  let input = useFloat16 ? x.to(.Float16) : x.to(.Float32)
  let upOut = scaleFactor.map { up((1 / $0) * input) } ?? up(input)
  let gateOut = gate(input)
  let product = h3DebugActivation(upOut .* gateOut.swish(), label: "\(prefix).product")
  let downOutput = down(product)
  let out = h3DebugActivation(
    useFloat16 ? downOutput.to(.Float32) : downOutput, label: "\(prefix).down")
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x], [out]), reader)
}

func h3FFNScaleFactor(layer: Int) -> Float? {
  // Measured on the complete 20-evaluation 256x256 T2VA trajectory. The restored
  // FP32 residual is unchanged; these factors only protect the FP16 FFN matmuls.
  if layer >= 45 { return 64 }
  if layer >= 39 { return 32 }
  if layer >= 36 { return 8 }
  if layer >= 12 { return 4 }
  return nil
}

func H3TransformerBlock(
  prefix: String, sequenceLength: Int, timestepCount: Int,
  scaleFactor: Float? = nil, useFloat16: Bool = false
) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  let rot = Input()
  let selection = Input()
  let activatedTimestep = Input()
  var modulationDense = [[Model]]()
  for chunk in 0..<6 {
    modulationDense.append(
      (0..<H3Config.modalityCount).map { modality in
        Dense(count: H3Config.hiddenSize, name: "adaln_\(chunk)_\(modality)")
      })
  }
  var modulations = [Model.IO]()
  for chunk in 0..<6 {
    let projected = modulationDense[chunk].enumerated().map { modality, dense in
      h3DebugActivation(
        dense(activatedTimestep), label: "\(prefix).adaln_\(chunk)_\(modality)")
    }
    var rows = [Model.IO]()
    for timestep in 0..<timestepCount {
      for modality in 0..<H3Config.modalityCount {
        rows.append(
          projected[modality].reshaped(
            [1, H3Config.hiddenSize], offset: [timestep, 0],
            strides: [H3Config.hiddenSize, 1]
          ).contiguous())
      }
    }
    var table = rows[0]
    for row in rows.dropFirst() {
      table = Functional.concat(axis: 0, table, row)
    }
    modulations.append(
      h3DebugActivation(
        Matmul()(selection.to(.Float32), table.to(.Float32))
          .reshaped([1, sequenceLength, H3Config.hiddenSize]),
        label: "\(prefix).modulation_\(chunk)"))
  }
  let norm1 = RMSNorm(epsilon: H3Config.normEpsilon, axis: [2], name: "norm1")
  let (attention, attentionReader) = H3Attention(
    prefix: "\(prefix).attn", sequenceLength: sequenceLength, rotary: true,
    useFloat16: useFloat16)
  let normed1 = norm1(x.to(.Float32))
  let scale1 = 1 + modulations[1]
  var out = h3DebugActivation(
    normed1 .* scale1 + modulations[0], label: "\(prefix).attn_input")
  let attentionInput = useFloat16 ? out.to(.Float16) : out
  out = x.to(.Float32) + modulations[2] .* attention(attentionInput, rot)
  out = h3DebugActivation(out, label: "\(prefix).post_attn")
  let residual = out
  let norm2 = RMSNorm(epsilon: H3Config.normEpsilon, axis: [2], name: "norm2")
  let (feedForward, feedForwardReader) = H3SwiGLU(
    prefix: "\(prefix).ff", scaleFactor: scaleFactor, useFloat16: useFloat16)
  let normed2 = norm2(out)
  let scale2 = 1 + modulations[4]
  out = normed2 .* scale2 + modulations[3]
  let feedForwardInput = useFloat16 ? out.to(.Float16) : out
  let feedForwardOutput = modulations[5] .* feedForward(feedForwardInput)
  if let scaleFactor {
    out = residual + scaleFactor * feedForwardOutput
  } else {
    out = residual + feedForwardOutput
  }
  out = h3DebugActivation(out, label: "\(prefix).output")
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x, rot, selection, activatedTimestep], [out]), reader)
}

func H3TokenRefinerBlock(
  prefix: String, sequenceLength: Int, useFloat16: Bool = false
) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  let norm1 = RMSNorm(epsilon: H3Config.normEpsilon, axis: [2], name: "refiner_norm1")
  let (attention, attentionReader) = H3Attention(
    prefix: "\(prefix).attn", sequenceLength: sequenceLength, rotary: false,
    useFloat16: useFloat16, name: "refiner")
  let attentionInput = h3DebugActivation(
    norm1(x.to(.Float32)), label: "\(prefix).attn_input")
  let attentionOutput = attention(useFloat16 ? attentionInput.to(.Float16) : attentionInput)
  var out = h3DebugActivation(
    x.to(.Float32) + attentionOutput, label: "\(prefix).post_attn")
  let norm2 = RMSNorm(epsilon: H3Config.normEpsilon, axis: [2], name: "refiner_norm2")
  let (feedForward, feedForwardReader) = H3SwiGLU(
    prefix: "\(prefix).ff", useFloat16: useFloat16, name: "refiner")
  let feedForwardInput = h3DebugActivation(norm2(out), label: "\(prefix).ff_input")
  let feedForwardOutput = feedForward(
    useFloat16 ? feedForwardInput.to(.Float16) : feedForwardInput)
  out = h3DebugActivation(out + feedForwardOutput, label: "\(prefix).output")
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x], [out]), reader)
}

func H3TokenRefiner(
  sequenceLength: Int, useFloat16: Bool = false
) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  var out: Model.IO = x
  var readers = [(PythonObject) -> Void]()
  for layer in 0..<H3Config.refinerLayers {
    let (block, reader) = H3TokenRefinerBlock(
      prefix: "token_refiner.refiner_blocks.\(layer)", sequenceLength: sequenceLength,
      useFloat16: useFloat16)
    out = block(out)
    readers.append(reader)
  }
  let norm = RMSNorm(epsilon: H3Config.normEpsilon, axis: [2], name: "refiner_final_norm")
  out = norm(out)
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x], [out]), reader)
}

func H3TimestepEmbedding(timestepCount: Int) -> (Model, (PythonObject) -> Void) {
  let frequencies = Input()
  let linear1 = Dense(
    count: H3Config.timestepHiddenSize, name: "time_embedder_linear_1")
  let linear2 = Dense(count: H3Config.timestepSize, name: "time_embedder_linear_2")
  let out = h3DebugActivation(
    linear2(linear1(frequencies).swish()), label: "time_embedder.output")
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([frequencies], [out]), reader)
}

func H3JointTransformer(
  textLength: Int, audioLength: Int, videoLength: Int, timestepCount: Int,
  layers: Int = H3Config.layers, includeHidden: Bool = false, useFloat16: Bool = false
) -> (Model, (PythonObject) -> Void) {
  let video = Input()
  let audio = Input()
  let text = Input()
  let rot = Input()
  let adalnSelection = Input()
  let timestepSelection = Input()
  let timestepFrequencies = Input()
  let sequenceLength = textLength + audioLength + videoLength

  let (timeEmbedding, timeEmbeddingReader) = H3TimestepEmbedding(timestepCount: timestepCount)
  let temb = timeEmbedding(timestepFrequencies)

  // Production uses scaled FP16 input projections and restores their outputs to FP32.
  let videoInput = Dense(
    count: H3Config.hiddenSize, flags: useFloat16 ? [.Float16] : [], name: "proj_in")
  let audioInput = Dense(
    count: H3Config.hiddenSize, flags: useFloat16 ? [.Float16] : [], name: "audio_proj_in")
  let textInput = Dense(
    count: H3Config.hiddenSize, flags: useFloat16 ? [.Float16] : [], name: "context_embedder")
  let inputProjectionScale: Float = useFloat16 ? 4 : 1
  let (refiner, refinerReader) = H3TokenRefiner(
    sequenceLength: textLength, useFloat16: useFloat16)
  let rawTextProjected = textInput(useFloat16 ? text.to(.Float16) : text.to(.Float32))
  let textProjected = h3DebugActivation(
    useFloat16 ? inputProjectionScale * rawTextProjected.to(.Float32) : rawTextProjected,
    label: "token_refiner.text_projection")
  let rawAudioProjected = audioInput(useFloat16 ? audio.to(.Float16) : audio)
  let rawVideoProjected = videoInput(useFloat16 ? video.to(.Float16) : video)
  let audioProjected =
    useFloat16 ? inputProjectionScale * rawAudioProjected.to(.Float32) : rawAudioProjected
  let videoProjected =
    useFloat16 ? inputProjectionScale * rawVideoProjected.to(.Float32) : rawVideoProjected
  let textRows = refiner(useFloat16 ? textProjected.to(.Float32) : textProjected)
  let audioRows = h3DebugActivation(audioProjected, label: "dit.audio_input")
  let videoRows = h3DebugActivation(videoProjected, label: "dit.video_input")
  var out = h3DebugActivation(
    Functional.concat(axis: 1, textRows, audioRows, videoRows), label: "dit.input")
  let activatedTemb = h3DebugActivation(temb.swish().to(.Float32), label: "dit.temb_activated")
  var readers = [(PythonObject) -> Void]()
  for layer in 0..<layers {
    let (block, reader) = H3TransformerBlock(
      prefix: "transformer_blocks.\(layer)", sequenceLength: sequenceLength,
      timestepCount: timestepCount,
      scaleFactor: useFloat16 ? h3FFNScaleFactor(layer: layer) : nil,
      useFloat16: useFloat16)
    out = block(out, rot, adalnSelection, activatedTemb)
    readers.append(reader)
  }
  // Do not construct this diagnostic edge for export-only models. ccv counts every
  // outgoing edge during functional graph traversal, including an unreturned edge.
  let preNorm = includeHidden ? out.to(.Float32) : nil

  let outputNorm = RMSNorm(epsilon: H3Config.normEpsilon, axis: [2], name: "norm_out")
  let outputShift = Dense(count: H3Config.hiddenSize, name: "norm_out_shift")
  let outputScale = Dense(count: H3Config.hiddenSize, name: "norm_out_scale")
  let shift = Matmul()(timestepSelection.to(.Float32), outputShift(activatedTemb))
    .reshaped([1, sequenceLength, H3Config.hiddenSize])
  let scale = Matmul()(timestepSelection.to(.Float32), outputScale(activatedTemb))
    .reshaped([1, sequenceLength, H3Config.hiddenSize])
  out = h3DebugActivation(outputNorm(out) .* (1 + scale) + shift, label: "dit.norm_out")
  let audioOutRows = out.reshaped(
    [1, audioLength, H3Config.hiddenSize], offset: [0, textLength, 0],
    strides: [sequenceLength * H3Config.hiddenSize, H3Config.hiddenSize, 1]
  ).contiguous().to(.Float32)
  let videoOutRows = out.reshaped(
    [1, videoLength, H3Config.hiddenSize], offset: [0, textLength + audioLength, 0],
    strides: [sequenceLength * H3Config.hiddenSize, H3Config.hiddenSize, 1]
  ).contiguous().to(.Float32)
  let videoOutput = Dense(count: H3Config.videoPatchSize, name: "proj_out")
  let audioOutput = Dense(count: H3Config.audioChannels, name: "audio_proj_out")

  let reader: (PythonObject) -> Void = { _ in }
  let projectedVideo = h3DebugActivation(videoOutput(videoOutRows), label: "dit.video_output")
  let projectedAudio = h3DebugActivation(audioOutput(audioOutRows), label: "dit.audio_output")
  let outputs: [Model.IO] =
    includeHidden
    ? [projectedVideo, projectedAudio, preNorm!, out.to(.Float32)]
    : [projectedVideo, projectedAudio]
  return (
    Model(
      [video, audio, text, rot, adalnSelection, timestepSelection, timestepFrequencies], outputs),
    reader
  )
}

func h3ConditioningVideoCausalPad(_ x: Model.IO, spatial: Int = 1) -> Model.IO {
  var out = x
  if spatial > 0 {
    out = out.padded(
      .reflect, begin: [0, 0, 0, spatial, spatial],
      end: [0, 0, 0, spatial, spatial])
  }
  return out.padded(.zero, begin: [0, 0, 2, 0, 0], end: [0, 0, 0, 0, 0])
}

func h3ConditioningVideoFrameNorm(
  _ x: Model.IO, channels: Int, frames: Int, height: Int, width: Int, name: String
) -> (GroupNorm, Model.IO) {
  let norm = GroupNorm(
    axis: 1, groups: 32, epsilon: H3ConditioningVideoEncoderConfig.normEpsilon,
    reduce: [2, 3], name: name)
  let framesAsBatch = x.permuted(0, 2, 1, 3, 4).copied()
    .reshaped([frames, channels, height, width])
  let normalized = norm(framesAsBatch)
  return (
    norm,
    normalized.reshaped([1, frames, channels, height, width])
      .permuted(0, 2, 1, 3, 4).copied()
  )
}

func H3ConditioningVideoResBlock(
  prefix: String, inChannels: Int, outChannels: Int,
  frames: Int, height: Int, width: Int
) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  let (norm1, normalized1) = h3ConditioningVideoFrameNorm(
    x, channels: inChannels, frames: frames, height: height, width: width, name: "norm1")
  let conv1 = Convolution(
    groups: 1, filters: outChannels, filterSize: [3, 3, 3],
    hint: Hint(stride: [1, 1, 1]), name: "conv1")
  var out = conv1(h3ConditioningVideoCausalPad(normalized1.swish()))
  let (norm2, normalized2) = h3ConditioningVideoFrameNorm(
    out, channels: outChannels, frames: frames, height: height, width: width, name: "norm2")
  let conv2 = Convolution(
    groups: 1, filters: outChannels, filterSize: [3, 3, 3],
    hint: Hint(stride: [1, 1, 1]), name: "conv2")
  out = conv2(h3ConditioningVideoCausalPad(normalized2.swish()))
  let shortcut: Convolution?
  if inChannels != outChannels {
    let projection = Convolution(
      groups: 1, filters: outChannels, filterSize: [1, 1, 1],
      hint: Hint(stride: [1, 1, 1]), name: "nin_shortcut")
    out = projection(x) + out
    shortcut = projection
  } else {
    out = x + out
    shortcut = nil
  }
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x], [out]), reader)
}

func H3ConditioningVideoEncoder(frames: Int, height: Int, width: Int)
  -> (Model, (PythonObject) -> Void)
{
  precondition(frames > 0 && height % 16 == 0 && width % 16 == 0)
  let x = Input()
  let convIn = Convolution(
    groups: 1, filters: 128, filterSize: [3, 3, 3],
    hint: Hint(stride: [1, 1, 1]), name: "conv_in")
  var out = convIn(h3ConditioningVideoCausalPad(x))
  var currentChannels = 128
  var currentFrames = frames
  var currentHeight = height
  var currentWidth = width
  var readers = [(PythonObject) -> Void]()
  for level in 0..<H3ConditioningVideoEncoderConfig.channels.count {
    let targetChannels = H3ConditioningVideoEncoderConfig.channels[level]
    for blockIndex in 0..<H3ConditioningVideoEncoderConfig.blocksPerLevel {
      let (block, reader) = H3ConditioningVideoResBlock(
        prefix: "encoder.down.\(level).block.\(blockIndex)",
        inChannels: currentChannels, outChannels: targetChannels,
        frames: currentFrames, height: currentHeight, width: currentWidth)
      out = block(out)
      currentChannels = targetChannels
      readers.append(reader)
    }
    let temporalStride = H3ConditioningVideoEncoderConfig.temporalStrides[level]
    let spatialStride = H3ConditioningVideoEncoderConfig.spatialStrides[level]
    if temporalStride * spatialStride > 1 {
      let downsample = Convolution(
        groups: 1, filters: currentChannels, filterSize: [3, 3, 3],
        hint: Hint(stride: [temporalStride, spatialStride, spatialStride]),
        name: "downsample_\(level)")
      if spatialStride == 2 {
        out = out.padded(
          .reflect, begin: [0, 0, 0, 0, 0], end: [0, 0, 0, 1, 1])
      }
      out = downsample(
        out.padded(.zero, begin: [0, 0, 2, 0, 0], end: [0, 0, 0, 0, 0]))
      readers.append { _ in }
      currentFrames = (currentFrames + temporalStride - 1) / temporalStride
      currentHeight /= spatialStride
      currentWidth /= spatialStride
    }
  }
  let (normOut, normalizedOut) = h3ConditioningVideoFrameNorm(
    out, channels: currentChannels, frames: currentFrames,
    height: currentHeight, width: currentWidth, name: "norm_out")
  let convOut = Convolution(
    groups: 1, filters: 48, filterSize: [3, 3, 3],
    hint: Hint(stride: [1, 1, 1]), name: "conv_out")
  out = convOut(h3ConditioningVideoCausalPad(normalizedOut.swish()))
  let quant = Convolution(
    groups: 1, filters: 48, filterSize: [1, 1, 1],
    hint: Hint(stride: [1, 1, 1]), name: "quant_conv")
  out = quant(out)
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x], [out]), reader)
}

func H3ConditioningAudioSnake(prefix: String, channels: Int, name: String)
  -> (Model, (PythonObject) -> Void)
{
  let x = Input()
  let alpha = Parameter<Float>(
    .GPU(deviceID), .NCHW(1, channels, 1, 1), trainable: false, name: "\(name)_alpha")
  let reciprocal = Parameter<Float>(
    .GPU(deviceID), .NCHW(1, channels, 1, 1), trainable: false,
    name: "\(name)_reciprocal")
  let out = x + reciprocal .* (alpha .* x).sin().pow(2)
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x], [out]), reader)
}

func H3ConditioningAudioResidualUnit(
  prefix: String, channels: Int, width: Int, dilation: Int, name: String
) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  let (snake1, snake1Reader) = H3ConditioningAudioSnake(
    prefix: "\(prefix).block.0", channels: channels, name: "\(name)_snake1")
  let conv1 = Convolution(
    groups: 1, filters: channels, filterSize: [1, 7], dilation: [1, dilation],
    hint: Hint(
      stride: [1, 1],
      border: Hint.Border(
        begin: [0, 3 * dilation], end: [0, 3 * dilation])), name: "\(name)_conv1")
  let (snake2, snake2Reader) = H3ConditioningAudioSnake(
    prefix: "\(prefix).block.2", channels: channels, name: "\(name)_snake2")
  let conv2 = Convolution(
    groups: 1, filters: channels, filterSize: [1, 1],
    hint: Hint(stride: [1, 1]), name: "\(name)_conv2")
  let out = x + conv2(snake2(conv1(snake1(x))))
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x], [out]), reader)
}

func H3ConditioningAudioEncoderBlock(
  prefix: String, channels: Int, outputChannels: Int, width: Int, stride: Int, name: String
) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  var out: Model.IO = x
  var readers = [(PythonObject) -> Void]()
  for (index, dilation) in [1, 3, 9].enumerated() {
    let (unit, reader) = H3ConditioningAudioResidualUnit(
      prefix: "\(prefix).\(index)", channels: channels, width: width,
      dilation: dilation, name: "\(name)_res\(index)")
    out = unit(out)
    readers.append(reader)
  }
  let (snake, snakeReader) = H3ConditioningAudioSnake(
    prefix: "\(prefix).3", channels: channels, name: "\(name)_snake")
  let downsample = Convolution(
    groups: 1, filters: outputChannels, filterSize: [1, 2 * stride],
    hint: Hint(
      stride: [1, stride],
      border: Hint.Border(
        begin: [0, (stride + 1) / 2], end: [0, (stride + 1) / 2])),
    name: "\(name)_downsample")
  out = downsample(snake(out))
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x], [out]), reader)
}

func H3ConditioningAudioProjection(length: Int) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  let norm1 = LayerNorm(epsilon: 1e-5, axis: [2], name: "norm1")
  let qkv = Dense(count: 6_144, name: "qkv")
  let projectedQKV = qkv(norm1(x))
  let q = projectedQKV.reshaped(
    [1, length, 2_048], offset: [0, 0, 0],
    strides: [length * 6_144, 6_144, 1]
  ).contiguous().reshaped(.NHWC(1, length, 8, 256))
  let k = projectedQKV.reshaped(
    [1, length, 2_048], offset: [0, 0, 2_048],
    strides: [length * 6_144, 6_144, 1]
  ).contiguous().reshaped(.NHWC(1, length, 8, 256))
  let v = projectedQKV.reshaped(
    [1, length, 2_048], offset: [0, 0, 4_096],
    strides: [length * 6_144, 6_144, 1]
  ).contiguous().reshaped(.NHWC(1, length, 8, 256))
  var attended = ScaledDotProductAttention(
    scale: 1 / Float(256).squareRoot(), isCausal: true)(
      q.to(.BFloat16), k.to(.BFloat16), v.to(.BFloat16)
    ).to(.Float32)
  attended = attended.reduced(.mean, axis: [2]).reshaped([1, length, 32, 8])
    .reduced(.mean, axis: [3]).reshaped([1, length, 32])
  let attentionOutput = Dense(count: 32, name: "attention_output")
  attended = attentionOutput(attended)
  let norm3 = LayerNorm(epsilon: 1e-5, axis: [2], name: "norm3")
  let inputProjection = Dense(count: 32, name: "input_projection")
  var out = inputProjection(norm3(x)) + attended
  let norm2 = LayerNorm(epsilon: 1e-5, axis: [2], name: "norm2")
  let mlpNorm = LayerNorm(epsilon: 1e-5, axis: [2], name: "mlp_norm")
  let mlpGate = Dense(count: 64, name: "mlp_gate")
  let mlpUp = Dense(count: 64, name: "mlp_up")
  let mlpDown = Dense(count: 32, name: "mlp_down")
  let mlpInput = mlpNorm(norm2(out))
  out = out + mlpDown(mlpGate(mlpInput).GELU(approximate: .tanh) .* mlpUp(mlpInput))
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x], [out]), reader)
}

func H3ConditioningAudioEncoder(inputLength: Int, includeHidden: Bool = false)
  -> (Model, (PythonObject) -> Void)
{
  precondition(inputLength > 0 && inputLength % 800 == 0)
  let x = Input()
  let input = Convolution(
    groups: 1, filters: 64, filterSize: [1, 7],
    hint: Hint(stride: [1, 1], border: Hint.Border(begin: [0, 3], end: [0, 3])),
    name: "encoder_input")
  var out = input(x)
  var width = inputLength
  var channels = 64
  var readers = [(PythonObject) -> Void]()
  for (level, stride) in [2, 4, 4, 5, 5].enumerated() {
    let (block, reader) = H3ConditioningAudioEncoderBlock(
      prefix: "encoder.block.\(level + 1).block", channels: channels,
      outputChannels: channels * 2, width: width, stride: stride,
      name: "encoder_block_\(level)")
    out = block(out)
    channels *= 2
    width /= stride
    readers.append(reader)
  }
  let (finalSnake, finalSnakeReader) = H3ConditioningAudioSnake(
    prefix: "encoder.block.6", channels: channels, name: "encoder_final_snake")
  let finalConv = Convolution(
    groups: 1, filters: 2_048, filterSize: [1, 3],
    hint: Hint(stride: [1, 1], border: Hint.Border(begin: [0, 1], end: [0, 1])),
    name: "encoder_final_conv")
  out = finalConv(finalSnake(out)).permuted(0, 3, 1, 2).copied()
    .reshaped([1, width, 2_048])
  let encoderOutput = out
  let (projection, projectionReader) = H3ConditioningAudioProjection(length: width)
  out = projection(out)
  let projected = out
  let mean = Dense(count: 32, name: "mean_proj")
  let logs = Dense(count: 32, name: "logs_proj")
  let output = Functional.concat(axis: 2, mean(out), logs(out))
  let reader: (PythonObject) -> Void = { _ in }
  return (
    Model([x], includeHidden ? [output, encoderOutput, projected] : [output]), reader
  )
}

func H3VideoDecoderAttention(prefix: String, sequenceLength: Int) -> (Model, (PythonObject) -> Void)
{
  let x = Input()
  let rot = Input()
  let q = Dense(count: H3VideoDecoderConfig.width, name: "to_q")
  let k = Dense(count: H3VideoDecoderConfig.width, name: "to_k")
  let v = Dense(count: H3VideoDecoderConfig.width, name: "to_v")
  let qNorm = RMSNorm(
    epsilon: H3VideoDecoderConfig.normEpsilon, axis: [3], elementwiseAffine: false)
  let kNorm = RMSNorm(
    epsilon: H3VideoDecoderConfig.normEpsilon, axis: [3], elementwiseAffine: false)
  var queries = q(x).reshaped(
    .NHWC(
      1, sequenceLength, H3VideoDecoderConfig.heads, H3VideoDecoderConfig.headDim))
  var keys = k(x).reshaped(
    .NHWC(
      1, sequenceLength, H3VideoDecoderConfig.heads, H3VideoDecoderConfig.headDim))
  let values = v(x).reshaped(
    .NHWC(
      1, sequenceLength, H3VideoDecoderConfig.heads, H3VideoDecoderConfig.headDim))
  queries = Functional.cmul(left: qNorm(queries.to(.Float32)).to(.Float16), right: rot)
  keys = Functional.cmul(left: kNorm(keys.to(.Float32)).to(.Float16), right: rot)
  let attention = ScaledDotProductAttention(
    scale: 1 / Float(H3VideoDecoderConfig.headDim).squareRoot(), flags: [.Float16])
  let attended = attention(queries, keys, values).reshaped([
    sequenceLength, H3VideoDecoderConfig.width,
  ])
  let output = Dense(count: H3VideoDecoderConfig.width, name: "to_out")
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x, rot], [output(attended)]), reader)
}

func H3VideoDecoderBlock(
  prefix: String, sequenceLength: Int, deviceID: Int
) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  let rot = Input()
  let norm1 = RMSNorm(
    epsilon: H3VideoDecoderConfig.normEpsilon, axis: [2], name: "norm1")
  let (attention, attentionReader) = H3VideoDecoderAttention(
    prefix: "\(prefix).attn", sequenceLength: sequenceLength)
  let scale1 = Parameter<Float>(
    .GPU(deviceID), .HWC(1, 1, H3VideoDecoderConfig.width), name: "scale1")
  var out =
    x.to(.Float32)
    + attention(norm1(x.to(.Float32)).to(.Float16), rot).to(.Float32) .* scale1
  let residual = out
  let norm2 = RMSNorm(
    epsilon: H3VideoDecoderConfig.normEpsilon, axis: [2], name: "norm2")
  let up = Dense(count: H3VideoDecoderConfig.intermediateSize, name: "ff_up")
  let gate = Dense(count: H3VideoDecoderConfig.intermediateSize, name: "ff_gate")
  let down = Dense(count: H3VideoDecoderConfig.width, name: "ff_down")
  let normed = norm2(out.to(.Float32)).to(.Float16)
  let scale2 = Parameter<Float>(
    .GPU(deviceID), .HWC(1, 1, H3VideoDecoderConfig.width), name: "scale2")
  out = residual + down(up(normed) .* gate(normed).swish()).to(.Float32) .* scale2
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x, rot], [out]), reader)
}

func H3VideoDecoder(
  numPatches: Int, deviceID: Int, layers: Int = H3VideoDecoderConfig.layers,
  includeHidden: Bool = false
) -> (Model, (PythonObject) -> Void) {
  let latentTokens = Input()
  let rot = Input()
  let zeroToken = Input()
  let postQuant = Dense(count: H3Config.videoChannels, name: "post_quant_conv")
  let input = Dense(count: H3VideoDecoderConfig.width, name: "decoder_proj_in")
  var out = input(postQuant(latentTokens)).to(.Float32)
  let registers = Parameter<Float>(
    .GPU(deviceID), .HWC(1, H3VideoDecoderConfig.registerTokens, H3VideoDecoderConfig.width),
    name: "register_tokens")
  out = Functional.concat(axis: 1, out, registers, zeroToken)
  let sequenceLength = numPatches + H3VideoDecoderConfig.registerTokens + 1
  var readers = [(PythonObject) -> Void]()
  for layer in 0..<layers {
    let (block, reader) = H3VideoDecoderBlock(
      prefix: "decoder.transformer_blocks.\(layer)", sequenceLength: sequenceLength,
      deviceID: deviceID)
    out = block(out, rot)
    readers.append(reader)
  }
  let hidden = out
  let norm = LayerNorm(
    epsilon: H3VideoDecoderConfig.normEpsilon, axis: [2], name: "decoder_norm_out")
  out = norm(out.to(.Float32)).to(.Float16)
  let output = Dense(
    count: 3 * H3VideoDecoderConfig.temporalPatch * H3VideoDecoderConfig.spatialPatch
      * H3VideoDecoderConfig.spatialPatch,
    name: "decoder_proj_out")
  out = output(out).reshaped(
    [
      1, numPatches,
      3 * H3VideoDecoderConfig.temporalPatch
        * H3VideoDecoderConfig.spatialPatch * H3VideoDecoderConfig.spatialPatch,
    ],
    offset: [0, 0, 0],
    strides: [
      sequenceLength * 3 * H3VideoDecoderConfig.temporalPatch
        * H3VideoDecoderConfig.spatialPatch * H3VideoDecoderConfig.spatialPatch,
      3 * H3VideoDecoderConfig.temporalPatch * H3VideoDecoderConfig.spatialPatch
        * H3VideoDecoderConfig.spatialPatch, 1,
    ]
  ).contiguous()
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([latentTokens, rot, zeroToken], includeHidden ? [out, hidden] : [out]), reader)
}

func H3AudioSnakeBeta(prefix: String, channels: Int, name: String) -> (
  (PythonObject) -> Void, Model
) {
  let x = Input()
  let alpha = Parameter<Float>(
    .GPU(deviceID), .NCHW(1, channels, 1, 1), trainable: false, name: "\(name)_alpha")
  let beta = Parameter<Float>(
    .GPU(deviceID), .NCHW(1, channels, 1, 1), trainable: false, name: "\(name)_beta")
  let out = x + beta .* (x .* alpha).sin().pow(2)
  let reader: (PythonObject) -> Void = { _ in }
  return (reader, Model([x], [out]))
}

func H3AudioActivation(
  prefix: String, channels: Int, width: Int, name: String
) -> ((PythonObject) -> Void, Model) {
  let x = Input()
  let ratio = 2
  let kernelSize = 12
  let upWidth = width * ratio
  let pad = kernelSize / ratio - 1
  let inputWidth = width + 2 * pad
  let rawWidth = (inputWidth - 1) * ratio + kernelSize
  let padLeft = pad * ratio + (kernelSize - ratio) / 2
  let upsample = ConvolutionTranspose(
    groups: 1, filters: 1, filterSize: [1, kernelSize], noBias: true,
    hint: Hint(stride: [1, ratio]), name: "\(name)_upsample")
  let (snakeReader, snake) = H3AudioSnakeBeta(
    prefix: "\(prefix).act", channels: channels, name: "\(name)_snake")
  let downsample = Convolution(
    groups: 1, filters: 1, filterSize: [1, kernelSize], noBias: true,
    hint: Hint(stride: [1, ratio]), name: "\(name)_downsample")
  var out = x.reshaped([channels, 1, 1, width])
  out = out.padded(.replicate, begin: [0, 0, 0, pad], end: [0, 0, 0, pad])
  out = Float(ratio) * upsample(out)
  out = out.reshaped(
    [channels, 1, 1, upWidth], offset: [0, 0, 0, padLeft],
    strides: [rawWidth, rawWidth, rawWidth, 1]
  ).contiguous()
  out = snake(out.reshaped([1, channels, 1, upWidth]))
  out = out.reshaped([channels, 1, 1, upWidth])
  out = downsample(
    out.padded(.replicate, begin: [0, 0, 0, 5], end: [0, 0, 0, 6]))
  out = out.reshaped([1, channels, 1, width])
  let reader: (PythonObject) -> Void = { _ in }
  return (reader, Model([x], [out]))
}

func H3AudioAMPBlock(
  prefix: String, channels: Int, width: Int, kernelSize: Int, name: String
) -> ((PythonObject) -> Void, Model) {
  let x = Input()
  var out: Model.IO = x
  var readers = [(PythonObject) -> Void]()
  for (index, dilation) in [1, 3, 5].enumerated() {
    let residual = out
    let (act1Reader, act1) = H3AudioActivation(
      prefix: "\(prefix).activations.\(index * 2)", channels: channels, width: width,
      name: "\(name)_a\(index)_0")
    let conv1 = Convolution(
      groups: 1, filters: channels, filterSize: [1, kernelSize], dilation: [1, dilation],
      hint: Hint(
        stride: [1, 1],
        border: Hint.Border(
          begin: [0, (kernelSize - 1) * dilation / 2],
          end: [0, (kernelSize - 1) * dilation / 2])), name: "\(name)_c\(index)_0")
    let (act2Reader, act2) = H3AudioActivation(
      prefix: "\(prefix).activations.\(index * 2 + 1)", channels: channels, width: width,
      name: "\(name)_a\(index)_1")
    let conv2 = Convolution(
      groups: 1, filters: channels, filterSize: [1, kernelSize],
      hint: Hint(
        stride: [1, 1],
        border: Hint.Border(
          begin: [0, (kernelSize - 1) / 2], end: [0, (kernelSize - 1) / 2])),
      name: "\(name)_c\(index)_1")
    out = residual + conv2(act2(conv1(act1(out))))
    readers.append(act1Reader)
    readers.append(act2Reader)
    readers.append { _ in }
  }
  return ({ _ in }, Model([x], [out]))
}

func H3AudioDecoder(latentWidth: Int) -> ((PythonObject) -> Void, Model) {
  let x = Input()
  let input = Convolution(
    groups: 1, filters: 2_048, filterSize: [1, 1],
    hint: Hint(stride: [1, 1]), name: "dec_in_proj")
  let pre = Convolution(
    groups: 1, filters: 1_024, filterSize: [1, 7],
    hint: Hint(stride: [1, 1], border: Hint.Border(begin: [0, 3], end: [0, 3])),
    name: "audio_conv_pre")
  var out = pre(input(x))
  let rates = [5, 5, 2, 2, 2, 2, 2]
  let kernels = [9, 9, 4, 4, 4, 4, 4]
  let resKernels = [3, 7, 11]
  var width = latentWidth
  var readers = [(PythonObject) -> Void]()
  for layer in 0..<rates.count {
    let channels = 1_024 / (1 << (layer + 1))
    let padding = (kernels[layer] - rates[layer]) / 2
    let up = ConvolutionTranspose(
      groups: 1, filters: channels, filterSize: [1, kernels[layer]],
      hint: Hint(
        stride: [1, rates[layer]],
        border: Hint.Border(begin: [0, padding], end: [0, padding])),
      name: "audio_up_\(layer)")
    out = up(out)
    width *= rates[layer]
    readers.append { _ in }
    var branches = [Model.IO]()
    for branch in 0..<resKernels.count {
      let blockIndex = layer * resKernels.count + branch
      let (reader, block) = H3AudioAMPBlock(
        prefix: "decoder.resblocks.\(blockIndex)", channels: channels, width: width,
        kernelSize: resKernels[branch], name: "audio_amp_\(blockIndex)")
      readers.append(reader)
      branches.append(block(out))
    }
    out = (1.0 / Float(branches.count)) * branches.dropFirst().reduce(branches[0]) { $0 + $1 }
  }
  let (postActivationReader, postActivation) = H3AudioActivation(
    prefix: "decoder.activation_post", channels: 8, width: width, name: "audio_post")
  readers.append(postActivationReader)
  out = postActivation(out)
  let post = Convolution(
    groups: 1, filters: 1, filterSize: [1, 7], noBias: true,
    hint: Hint(stride: [1, 1], border: Hint.Border(begin: [0, 3], end: [0, 3])),
    name: "audio_conv_post")
  out = post(out).clamped(-1...1)
  let reader: (PythonObject) -> Void = { _ in }
  return (reader, Model([x], [out]))
}

// This is the same Qwen3-VL decoder block structure already used by the Flux.2,
// Ideogram 4, Krea 2, and Anima conversions. H3 reads hidden_states[50] directly
// from the language model, so the conversion stops after block 49 in the composed
// encoder; this single-layer unit is also useful for mandatory numeric validation.
func H3QwenAttention(prefix: String, sequenceLength: Int) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  let rot = Input()
  let q = Dense(
    count: H3QwenConfig.heads * H3QwenConfig.headDim, noBias: true, name: "q_proj")
  let k = Dense(
    count: H3QwenConfig.keyValueHeads * H3QwenConfig.headDim, noBias: true, name: "k_proj")
  let v = Dense(
    count: H3QwenConfig.keyValueHeads * H3QwenConfig.headDim, noBias: true, name: "v_proj")
  let qNorm = RMSNorm(epsilon: H3QwenConfig.normEpsilon, axis: [3], name: "q_norm")
  let kNorm = RMSNorm(epsilon: H3QwenConfig.normEpsilon, axis: [3], name: "k_norm")
  var queries = q(x.to(.Float32)).reshaped(
    .NHWC(
      1, sequenceLength, H3QwenConfig.heads, H3QwenConfig.headDim))
  var keys = k(x.to(.Float32)).reshaped(
    .NHWC(
      1, sequenceLength, H3QwenConfig.keyValueHeads, H3QwenConfig.headDim))
  let values = v(x.to(.Float32)).reshaped(
    .NHWC(
      1, sequenceLength, H3QwenConfig.keyValueHeads, H3QwenConfig.headDim))
  queries = Functional.cmul(left: qNorm(queries), right: rot.to(.Float32))
  keys = Functional.cmul(left: kNorm(keys), right: rot.to(.Float32))
  let attention = ScaledDotProductAttention(
    scale: 1 / Float(H3QwenConfig.headDim).squareRoot(), isCausal: true)
  let attended = attention(
    queries.to(.BFloat16), keys.to(.BFloat16), values.to(.BFloat16)
  ).to(.Float32).reshaped([
    sequenceLength, H3QwenConfig.heads * H3QwenConfig.headDim,
  ])
  let output = Dense(count: H3QwenConfig.hiddenSize, noBias: true, name: "o_proj")
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x, rot], [output(attended)]), reader)
}

func H3QwenBlock(prefix: String, sequenceLength: Int) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  let rot = Input()
  let inputNorm = RMSNorm(
    epsilon: H3QwenConfig.normEpsilon, axis: [1], name: "input_layernorm")
  let (attention, attentionReader) = H3QwenAttention(
    prefix: "\(prefix).self_attn", sequenceLength: sequenceLength)
  var out = x.to(.Float32) + attention(inputNorm(x.to(.Float32)), rot)
  let residual = out
  let postAttentionNorm = RMSNorm(
    epsilon: H3QwenConfig.normEpsilon, axis: [1], name: "post_attention_layernorm")
  out = postAttentionNorm(out)
  let gate = Dense(count: H3QwenConfig.intermediateSize, noBias: true, name: "gate_proj")
  let up = Dense(count: H3QwenConfig.intermediateSize, noBias: true, name: "up_proj")
  let down = Dense(count: H3QwenConfig.hiddenSize, noBias: true, name: "down_proj")
  let gateOut = gate(out)
  let upOut = up(out)
  out = residual + down(gateOut.swish() .* upOut)
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x, rot], [out]), reader)
}

func H3QwenTextEncoder(sequenceLength: Int) -> (Model, (PythonObject) -> Void) {
  let tokens = Input()
  let rot = Input()
  let embedding = Embedding(
    BlockFloat.self, vocabularySize: H3QwenConfig.vocabularySize,
    embeddingSize: H3QwenConfig.hiddenSize, name: "tok_embeddings")
  var out = embedding(tokens)
  var readers = [(PythonObject) -> Void]()
  // hidden_states[0] is the embedding. H3 consumes hidden_states[50], hence the
  // un-normalized residual stream after decoder block 49.
  for layer in 0..<H3QwenConfig.featureLayer {
    let prefix = "model.language_model.layers.\(layer)"
    let (block, reader) = H3QwenBlock(prefix: prefix, sequenceLength: sequenceLength)
    out = block(out, rot)
    readers.append(reader)
  }
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([tokens, rot], [out]), reader)
}

// Standard Qwen3-VL FP16 store model. Names deliberately match the existing
// qwen_3_vl_4b / qwen_3_vl_8b stores under /slow/Data.
func H3QwenExportAttention(prefix: String, sequenceLength: Int) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  let rot = Input()
  let k = Dense(
    count: H3QwenConfig.keyValueHeads * H3QwenConfig.headDim, noBias: true, name: "k_proj")
  let q = Dense(
    count: H3QwenConfig.heads * H3QwenConfig.headDim, noBias: true, name: "q_proj")
  let v = Dense(
    count: H3QwenConfig.keyValueHeads * H3QwenConfig.headDim, noBias: true, name: "v_proj")
  var keys = k(x).reshaped(
    .NHWC(
      1, sequenceLength, H3QwenConfig.keyValueHeads, H3QwenConfig.headDim))
  let normK = RMSNorm(epsilon: H3QwenConfig.normEpsilon, axis: [3], name: "norm_k")
  keys = normK(keys)
  var queries = q(x).reshaped(
    .NHWC(
      1, sequenceLength, H3QwenConfig.heads, H3QwenConfig.headDim))
  let normQ = RMSNorm(epsilon: H3QwenConfig.normEpsilon, axis: [3], name: "norm_q")
  queries = normQ(queries)
  let values = v(x).reshaped(
    .NHWC(
      1, sequenceLength, H3QwenConfig.keyValueHeads, H3QwenConfig.headDim))
  queries = Functional.cmul(left: queries, right: rot)
  keys = Functional.cmul(left: keys, right: rot)
  let attended = ScaledDotProductAttention(
    scale: 1 / Float(H3QwenConfig.headDim).squareRoot(), isCausal: true)(
      queries, keys, values
    ).reshaped([sequenceLength, H3QwenConfig.heads * H3QwenConfig.headDim])
  let output = Dense(count: H3QwenConfig.hiddenSize, noBias: true, name: "out_proj")
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x, rot], [output(attended)]), reader)
}

func H3QwenExportBlock(prefix: String, sequenceLength: Int) -> (Model, (PythonObject) -> Void) {
  let x = Input()
  let rot = Input()
  let inputNorm = RMSNorm(
    epsilon: H3QwenConfig.normEpsilon, axis: [1], name: "input_layernorm")
  let (attention, attentionReader) = H3QwenExportAttention(
    prefix: prefix, sequenceLength: sequenceLength)
  var out = x + attention(inputNorm(x), rot)
  let residual = out
  let postNorm = RMSNorm(
    epsilon: H3QwenConfig.normEpsilon, axis: [1], name: "post_attention_layernorm")
  let mlpInput = Input()
  let gate = Dense(
    count: H3QwenConfig.intermediateSize, noBias: true, name: "mlp_gate_proj")
  let up = Dense(count: H3QwenConfig.intermediateSize, noBias: true, name: "mlp_up_proj")
  let down = Dense(count: H3QwenConfig.hiddenSize, noBias: true, name: "mlp_down_proj")
  let feedForward = Model(
    [mlpInput], [down(up(mlpInput) .* gate(mlpInput).swish())], name: "mlp")
  out = residual + feedForward(postNorm(out))
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([x, rot], [out]), reader)
}

func H3QwenExportModel(sequenceLength: Int) -> (Model, (PythonObject) -> Void) {
  let tokens = Input()
  let rot = Input()
  let embedding = Embedding(
    Float16.self, vocabularySize: H3QwenConfig.vocabularySize,
    embeddingSize: H3QwenConfig.hiddenSize, name: "tok_embeddings")
  var out = embedding(tokens)
  var readers = [(PythonObject) -> Void]()
  for layer in 0..<H3QwenConfig.featureLayer {
    let prefix = "model.language_model.layers.\(layer)"
    let (block, reader) = H3QwenExportBlock(prefix: prefix, sequenceLength: sequenceLength)
    out = block(out, rot)
    readers.append(reader)
  }
  let reader: (PythonObject) -> Void = { _ in }
  return (Model([tokens, rot], [out]), reader)
}
